### ISSUE TITLE
Typo - Page 77

### ISSUE THREAD

**Issue by Atralb** [learnbyexample/learn_gnugrep_ripgrep#1]
Page 77
Paragraph 1
Line 4

Actual text :

"behavior varies wrt GNU grep in terms
of features"

Expected text :
"behavior varies **with** GNU grep in terms
of features"

PS : Thanks a lot for your quality work and the open access you gave to it. I'll try to stay alert and report any other typo or suggestions that may enter my mind.

**Comment by learnbyexample** [comment]
Hey, thanks for the issue.

However, in this case, I'm using `wrt` as an abbreviation for `with respect to`. See https://www.oxfordlearnersdictionaries.com/definition/english/wrt

But probably, it is good to expand it or use `w.r.t.` to be clear. So, I'll keep the issue open for now.

**Comment by Atralb** [comment]
Oh sorry for my mistake !

Yes, it's not so clear without delimiters. Then again, I'm not familiar with this abbreviation. But again sorry for the waste of time :\

**Comment by learnbyexample** [comment]
Hey, this isn't waste of time for me. This was a genuine confusion for you and that's a feedback I'd welcome :)
