### ISSUE TITLE
[preface] English mechanics

### ISSUE THREAD

**Issue by bound-variable** [learnbyexample/learn_gnugrep_ripgrep#4]
**One**

You are likely to be familiar with using Ctrl+F from an editor, word processor, web browser, IDE, etc **.,** to quickly locate where a particular string occurs.

- Reason: See [here](https://www.grammarly.com/blog/et-cetera-etc/#:~:text=A%20good%20way%20to%20test,the%20end%20of%20the%20sentence.)

---

**Two**

grep is **a** similar, but much more versatile and feature-rich version of ~~the~~ **that** search functionality usable from the command line.

- Reason: We're being told that grep is a functionality, that is, a countable noun; it requires an article. Also, _the_ is not the right word to refer to the Ctrl-F search functionality, since _the_ is **indefinite**, but we need the **definite**.

---

**Three**

Modern requirements have given rise to tools like ripgrep that provide out-of-box features such as recursive search while respecting **the** ignore rules of a version controlled directory.

- Reason: _ignore rules_ is not a mass noun here, since it refers to ones that belong to some _single_ version controlled directory.

---

**Four**

Understanding both the nature of sample input string and the output produced is essential.

- We shouldn't say this. _Sample input string_ is treated as a mass noun without an article, while _output_ is treated as definite. Hence, the sentence lacks parallelism. There are different ways to fix this. I'm not sure how you'd like it done.

---

**Five**

As an analogy, consider learning to ~~drive~~ **ride** a bike or **drive** a car

- Reason: We ride bikes and drive cars.

---

**Six**

Should you feel that copy-paste is ideal for you, [code snippets are available ~~chapter wise~~ **chapter-wise** on GitHub](https://github.com/learnbyexample/learn_gnugrep_ripgrep/tree/master/code_snippets).

- Reason: See **adverb combining form** [here](https://www.merriam-webster.com/dictionary/wise)

---

**Seven**

My [Command Line Text Processing](https://github.com/learnbyexample/Command-line-text-processing) repository includes a chapter on GNU grep **,** which has been edited and expanded to create this book.

- Reason: a comma is needed before _which_, see [here](https://www.grammarly.com/blog/comma-before-which/)

---

**Eight**

Prior experience working with **the** command line and bash shell ~~,~~ **.** **You** should know concepts like file redirection, command pipeline **,** and so on.

Reason: command line and bash shell require an article; they're not mass nouns. This sentence was also comma-spliced.

---

**Nine**

If you are new to the world of **the** command line, check out my curated resources on [Linux CLI and Shell scripting](https://learnbyexample.github.io/curated_resources/linux_cli_scripting.html) before starting this book.

Reason: Same as _eight_

---

**Ten**

I would highly appreciate **it** if you'd let me know how you felt about this book ~~,~~ **.** ~~it~~ **It** would help to improve this book as well as my future attempts. Also, please do let me know if you spot any ~~error~~ **errors** or ~~typo~~ **typos**.

- Reason: _appreciate_ is a transitive verb and needs an object. There's also a comma-splice. Lastly, _error_ and _typo_ are countable.

---

**Eleven**

You can find his other works, primarily focused on **the** Linux command line, text processing, scripting languages ~~and curated lists~~, at https://github.com/learnbyexample. He has also been a technical reviewer for **the** [Command Line Fundamentals](https://www.packtpub.com/application-development/command-line-fundamentals) book and video course published by Packt.

- Reason: _command line_ is not a mass noun. Also, it doesn't really make sense to say "my work is focused on curated lists". Perhaps people work on **curating** lists (they work on _doing_ something, i.e., _curating_), but they don't work on the _finished_ (curated) lists themselves. Lastly, _books_ are countable.

**Comment by learnbyexample** [comment]
Thanks, fixed as part of the new release.
