### ISSUE TITLE
Grammatical corrections

### ISSUE THREAD

**Issue by bound-variable** [learnbyexample/learn_gnugrep_ripgrep#5]
[introduction.md](https://github.com/learnbyexample/learn_gnugrep_ripgrep/files/8673644/introduction.md)

**Comment by bound-variable** [comment]
[freq_used_options.md](https://github.com/learnbyexample/learn_gnugrep_ripgrep/files/8757587/freq_used_options.md)

**Comment by learnbyexample** [comment]
Thanks, fixed as part of the new release.

**Comment by bound-variable** [comment]
You're welcome.

 

Thanks for the mention

 
 

Sent: Wednesday, May 10, 2023 at 8:59 PM
