### ISSUE TITLE
Using ANSI-C Quoting strings with grep

### ISSUE THREAD

**Issue by emptyTuple** [learnbyexample/learn_gnugrep_ripgrep#8]
Great job with RE! Thank you!
But, this part:
https://learnbyexample.github.io/learn_gnugrep_ripgrep/breere-regular-expressions.html#matching-characters-like-tabs

It seems no reliable way to use bash (or zsh) ANSI-C Quoting strings to catch sequences containing newline (\n).
It works perfectly with \t (and \v too) as you mentioned, even with quantifiers:
`echo -e '#xy x\ty x\t\ty#' | grep -E $'x\t*y'`

But doesn't work with newline \n properly, matching all the symbols from the pattern in any order all the time
`echo -e '#xy x\ny xxxyyy x\n\ny#' | grep -E $'x\ny'`

**Comment by learnbyexample** [comment]
`grep` by default works only line by line basis. So, you can never match a newline character.

There is a limited workaround possible by using the `-z` option - this uses the ASCII NUL character as the line separator and thus entire input will be treated as a single line (assuming input doesn't have any NUL character). See https://learnbyexample.github.io/learn_gnugrep_ripgrep/miscellaneous-options.html#multiline-matching for examples.

That said, I didn't understand your example. What is your expected output?

**Comment by emptyTuple** [comment]
I'm sorry, I'm a newbie with CLI shells and with Linux at all.
I expected the similar behaviour like with \t or precisely I assumed the pattern would catch the sequence 'x\ny' as the last symbol of the first line and the first symbol of the second. I'm wrong because grep works only line by line?

Something like with PCRE:
`echo -e 'XxyX Xx\nyX Xx yX Xx\nyX' | grep -Pz 'x(\s)*y'`
"X" was used to highlight xy-sequences I would like to match

**Comment by emptyTuple** [comment]
For example, let I have a file with a huge sequence of digits, some digits are separated by \t or \n one or more times or both in any order several times. And I have to match all occurrences of 42 even it is separated with \n, \t or both arbitrarily.
How can I catch them all?

**Comment by learnbyexample** [comment]
If you need to extract only the matching portions, use the `-o` option. For example:

```bash
$ echo -e 'XxyX Xx\nyX Xx yX Xx\nyX' | grep -oz 'x\s*y' | sed 's/\x0/\n---\n/g'
xy
---
x
y
---
x y
---
x
y
---
```

`sed` is used above to convert the NUL character in `grep` output to something else.

**Comment by emptyTuple** [comment]
done
